### ISSUE TITLE
NCCL Error of Reproducing Analytical Model

### ISSUE THREAD

**Issue by Comtive-Wdson** [LoongServe/LoongServe#5]
### Error Description
I have encountered an error while attempting to reproduce the Analytical Model and generate the final .sqlite3 file.
When executing the command `python3 ~/research/LongServe/test/longserve/1-benchmark-identical-req.py longserve-ae-analytical-model-single-node`, I am met with the following error:
```
node0:221535:221535 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
node0:221535:221535 [0] NCCL INFO Bootstrap : Using eno12399np0:128.105.146.44<0>
node0:221535:221535 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
node0:221535:221535 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
node0:221535:221535 [0] NCCL INFO NET/Plugin: Using internal network plugin.
(LongServeWorker pid=221896) (0, 0) Worker initializing with sp_rank = 0/1, tp_rank = 0/1, total_rank = 0/1
Traceback (most recent call last):
  File "/users/CWdson/research/LoongServe/test/longserve/1-benchmark-identical-req.py", line 455, in <module>
    test_group_candidates[select_test_group]()
  File "/users/CWdson/research/LoongServe/test/longserve/1-benchmark-identical-req.py", line 443, in <lambda>
    "longserve-ae-analytical-model-single-node": lambda: run_longserve(get_time_with_batch_size_params(False)),
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/CWdson/research/LoongServe/test/longserve/1-benchmark-identical-req.py", line 412, in run_longserve
    run_test_params(LongServeSUT, LOONGSERVE_DB_IDENTICAL_REQ_PATH, test_params, **kwargs)
  File "/users/CWdson/research/LoongServe/test/longserve/lib/run_test_param_group.py", line 40, in run_test_params
    sut = sut_class(worker_param)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/CWdson/research/LoongServe/test/longserve/lib/sut_longserve.py", line 146, in __init__
    ray.get(init_model_rets)
  File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(DistBackendError): ray::LongServeWorker.init_model() (pid=221896, ip=128.105.146.44, actor_id=0fc2a5b3a93c41ec4917807f01000000, repr=<lib.worker.LongServeWorker object at 0x7f1dc0c249b0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/users/CWdson/research/LoongServe/test/longserve/lib/worker.py", line 60, in init_model
    dist.all_reduce(dummy_tensor, op=dist.ReduceOp.SUM, group=model_kvargs["tp_group"], async_op=False)
  File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2501, in all_reduce
    work = group.allreduce([tensor], opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1729647406761/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2251, internal error - please report this issue to the NCCL developers, NCCL version 2.21.5
ncclInternalError: Internal check failed.
Last error:
Bootstrap : no socket interface found
```
### Versions
```
Architecture: x86_64
OS: Ubuntu 20.04
GPU: 4x 40GB A100 SXM4 GPUs
python: 3.12
Pytorch: 2.5.1
nvcc: 12.4
libnccl2: 2.22.3-1+cuda12.4
```
### Attempts Made
We have searched Google and have tried setting the `CUDA_VISIBLE_DEVICES`, `NCCL_SOCKET_IFNAME`,  `NCCL_IB_TIMEOUT` environment variables without success.
### Query
We noticed a similar error mentioned in your documentation for the Reproduce Figure 2 section, stemming from Ray's operations, but ours differs in that the final error is related to NCCL.
We suspect it might be an issue with the version of the NCCL library. Could you please provide the version of the NCCL library you are using and share any thoughts on how to resolve this issue?

**Comment by ZhangYunchenY** [comment]
same issue.

**Comment by myfortune110** [comment]
anyone solved this problem?

**Comment by hb-jw** [comment]
same issue, anyone solved the problem?

**Comment by SkyAur0ra** [comment]
Maybe you didn't adjust the NCCL_SOCKET_IFNAME to "eno12399np0" in **_worker.py_**? (Actually it's suppose to be your own ethernet interface's name)

> ### Error Description
> I have encountered an error while attempting to reproduce the Analytical Model and generate the final .sqlite3 file. When executing the command `python3 ~/research/LongServe/test/longserve/1-benchmark-identical-req.py longserve-ae-analytical-model-single-node`, I am met with the following error:
> 
> ```
> node0:221535:221535 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
> node0:221535:221535 [0] NCCL INFO Bootstrap : Using eno12399np0:128.105.146.44<0>
> node0:221535:221535 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
> node0:221535:221535 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
> node0:221535:221535 [0] NCCL INFO NET/Plugin: Using internal network plugin.
> (LongServeWorker pid=221896) (0, 0) Worker initializing with sp_rank = 0/1, tp_rank = 0/1, total_rank = 0/1
> Traceback (most recent call last):
>   File "/users/CWdson/research/LoongServe/test/longserve/1-benchmark-identical-req.py", line 455, in <module>
>     test_group_candidates[select_test_group]()
>   File "/users/CWdson/research/LoongServe/test/longserve/1-benchmark-identical-req.py", line 443, in <lambda>
>     "longserve-ae-analytical-model-single-node": lambda: run_longserve(get_time_with_batch_size_params(False)),
>                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/users/CWdson/research/LoongServe/test/longserve/1-benchmark-identical-req.py", line 412, in run_longserve
>     run_test_params(LongServeSUT, LOONGSERVE_DB_IDENTICAL_REQ_PATH, test_params, **kwargs)
>   File "/users/CWdson/research/LoongServe/test/longserve/lib/run_test_param_group.py", line 40, in run_test_params
>     sut = sut_class(worker_param)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/users/CWdson/research/LoongServe/test/longserve/lib/sut_longserve.py", line 146, in __init__
>     ray.get(init_model_rets)
>   File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/worker.py", line 2755, in get
>     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
>                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/ray/_private/worker.py", line 906, in get_objects
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(DistBackendError): ray::LongServeWorker.init_model() (pid=221896, ip=128.105.146.44, actor_id=0fc2a5b3a93c41ec4917807f01000000, repr=<lib.worker.LongServeWorker object at 0x7f1dc0c249b0>)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/users/CWdson/research/LoongServe/test/longserve/lib/worker.py", line 60, in init_model
>     dist.all_reduce(dummy_tensor, op=dist.ReduceOp.SUM, group=model_kvargs["tp_group"], async_op=False)
>   File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/nvm/anaconda3/envs/loongserve/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2501, in all_reduce
>     work = group.allreduce([tensor], opts)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1729647406761/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2251, internal error - please report this issue to the NCCL developers, NCCL version 2.21.5
> ncclInternalError: Internal check failed.
> Last error:
> Bootstrap : no socket interface found
> ```
> 
> ### Versions
> ```
> Architecture: x86_64
> OS: Ubuntu 20.04
> GPU: 4x 40GB A100 SXM4 GPUs
> python: 3.12
> Pytorch: 2.5.1
> nvcc: 12.4
> libnccl2: 2.22.3-1+cuda12.4
> ```
> 
> ### Attempts Made
> We have searched Google and have tried setting the `CUDA_VISIBLE_DEVICES`, `NCCL_SOCKET_IFNAME`, `NCCL_IB_TIMEOUT` environment variables without success.
> 
> ### Query
> We noticed a similar error mentioned in your documentation for the Reproduce Figure 2 section, stemming from Ray's operations, but ours differs in that the final error is related to NCCL. We suspect it might be an issue with the version of the NCCL library. Could you please provide the version of the NCCL library you are using and share any thoughts on how to resolve this issue?
